template_components:
  task_schemas:
  - objective: run_abaqus
    inputs:
    - parameter: friction
    - parameter: conductance
    - parameter: power
    - parameter: inp_file
    actions:
      - environments:
        - scope:
            type: any
          environment: abaqus_env
        input_file_generators:
        - input_file: new_inp_file
          from_inputs:
          - friction
          - conductance
          - power
          - inp_file
          script: <<script:/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/generate_input_file.py>>
        commands:
        - command: <<executable:abaqus>> job=sub_script_check input=<<file:new_inp_file>> interactive

  command_files:
  - label: new_inp_file
    name:
      name: friction_conductance.inp

tasks:
- schema: run_abaqus
  inputs:
    friction: 0.01
    conductance: [0,"/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/Abaqus_5_min_heatup/800nocondC_heatup22.odb"]
    power: 0
    inp_file: /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/800C_1s-1_setup.inp
