template_components:
  environments:
  - name: abaqus_env
    setup: |
      source /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/.venv/bin/activate
      module load apps/binapps/abaqus/2022
    executables:
    - label: python_script
      instances:
      - command: python <<script_name>> <<args>>
        num_cores: 1
        parallel_mode: null
    - label: abaqus
      instances:
      - command: abq2022
        num_cores: 1
        parallel_mode: null

  task_schemas:
  - objective: run_abaqus
    inputs:
    - parameter: friction
    - parameter: conductance_value
    - parameter: conductance_file
    - parameter: power
    - parameter: inp_file
    outputs:
    - parameter: combined_odb_results
    actions:
    - environments:
      - scope:
          type: any
        environment: abaqus_env
      input_file_generators:
      - input_file: new_inp_file
        from_inputs:
        - friction
        - conductance_value
        - conductance_file
        - power
        - inp_file
        script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/\
          Abaqus_bayesian_matflow/generate_input_file.py>>"
      commands:
      - command: <<executable:abaqus>> job=sub_script_check input=<<file:new_inp_file>> interactive
      - command: "<<executable:abaqus>> cae noGUI=/mnt/iusers01/support/mbexegc2/scratch/\
          Abaqus_bayesian_matflow/read_Force_PEEQ_NT11_barrelling_forcemac.py"
      save_files:
      - odb_file
      output_file_parsers:
        combined_odb_results:
          from_files:
          # These files have been removed from `save_files` in the main action above due to a bug.
          # They're automatically saved when they are listed as `from_files`.
          - force_sample_set_1
          - force_sample_set_2
          - nt11
          - outer_sample_xcoords
          - peeq_output
          script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/\
            Abaqus_bayesian_matflow/combine_odb_results.py>>"
          save_files:
          - odb_results
          inputs:
            - friction
            - conductance_value
            - power
  - objective: gather_odb_results
    inputs:
    - parameter: combined_odb_results
      group: property_combo
    outputs:
    - parameter: odb_results_table
    actions:
    - environments:
      - scope:
          type: any
        environment: abaqus_env
      script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/\
            Abaqus_bayesian_matflow/gather_odb_results.py>>"
      script_exe: python_script
      script_data_in: direct
      script_data_out: direct
      save_files:
      - odb_results_table
  - objective: create_model_data
    inputs:
    - parameter: odb_results_table
    - parameter: n_basis
    - parameter: plastic_start_step
    - parameter: plastic_end_step
    - parameter: train_to_validate
    outputs:
    - parameter: x_train
    - parameter: y_train
    - parameter: x_validate
    - parameter: y_validate
    actions: 
    - environments:
      - scope:
          type: any
        environment: abaqus_env
      script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/\
               Abaqus_bayesian_matflow/clean_profile_data.py>>"
      script_exe: python_script
      script_data_in: direct
      script_data_out: direct
      save_files:
      - x_pickle
      - y_pickle
  - objective: run_model
    inputs:
    - parameter: x_train
    - parameter: y_train
    - parameter: x_validate
    - parameter: y_validate
    - parameter: n_basis
    - parameter: kernel
    - parameter: model_name
    actions:
    - environments:
      - scope:
          type: any
        environment: abaqus_env
      script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/\
               Abaqus_bayesian_matflow/run_model.py>>"
      script_exe: python_script
      script_data_in: direct
  - objective: sample_model
    inputs:
    - parameter: x_pickle # command file - looks like I have to hack it by providing a relative path?
    - parameter: y_pickle # command file
    - parameter: n_basis
    - parameter: plastic_start_step
    - parameter: plastic_end_step
    - parameter: burn_in
    - parameter: sample_size
    - parameter: sythetic_mean_basis_coeffs
    - parameter: model_name
    - parameter: variance_dir
    actions:
    - environments:
      - scope:
          type: any
        environment: abaqus_env
      script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/\
               sample_model.py>>"
      script_exe: python_script
      script_data_in: direct


  command_files:
  - label: new_inp_file
    name:
      name: friction_conductance.inp
  - label: odb_file
    name:
      name: sub_script_check.odb
  - label: force_sample_set_1
    name:
      name: Force_sample_set1.rpt
  - label: force_sample_set_2
    name:
      name: Force_sample_set2.rpt
  - label: nt11
    name:
      name: NT11.rpt
  - label: outer_sample_xcoords
    name:
      name: outer_sample_xcoords.rpt
  - label: peeq_output
    name:
      name: PEEQ_output.rpt
  - label: odb_results
    name:
      name: odb_results.json
  - label: odb_results_table
    name:
      name: odb_results_table.json
  - label: x_pickle
    name:
      name: x.pkl
  - label: y_pickle
    name:
      name: y.pkl

resources:
  any:
    scheduler_args:
      options:
        -l: short

tasks:
- schema: run_abaqus
  groups:
  - name: property_combo
  inputs:
    power: 0
    inp_file: /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/800C_1s-1_setup.inp
  sequences:
  - path: inputs.conductance_value
    values:
    - 0
    - 100
    - 200
    nesting_order: 0
  - path: inputs.conductance_file
    values:
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/800nocondC_heatup22.odb"
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/80010C_heatup22.odb"
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/80020C_heatup22.odb"
    nesting_order: 0
  - path: inputs.friction
    values:
    - 0.01
    - 0.08
    - 0.15
#    - 0.22
#    - 0.29
#    - 0.36
#    - 0.43
#    - 0.5
#    - 0.57
#    - 0.64
#    - 0.71
#    - 0.78
#    - 0.85
#    - 0.92
#    - 0.99
    nesting_order: 1
- schema: gather_odb_results
- schema: create_model_data
  inputs:
   n_basis: 2
   plastic_start_step: 4
   plastic_end_step: -1
   train_to_validate: 0.8
- schema: run_model
  inputs:
    n_basis: 2
    kernel: Auto
    model_name: Quadplast_timesteps_5-15
- schema: sample_model
  inputs:
    x_pickle: ../../../../artifacts/tasks/task_2_create_model_data/e_0/r_0/x.pkl
    y_pickle: ../../../../artifacts/tasks/task_2_create_model_data/e_0/r_0/y.pkl
    plastic_start_step: 4
#    n_basis: 2 # Does this need to be specified, or will it be "read" from previous tasks inputs?
    plastic_end_step: 15
    burn_in: 100000
    sample_size: 200000
    sythetic_mean_basis_coeffs: [46973769.8, 322884.150]
    model_name: Quadplast_timesteps_5-15
    variance_dir: Ti64_Flowcurves
