template_components:
  environments:
  - name: abaqus_env
    setup: |
      source /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/.venv/bin/activate
      module load apps/binapps/abaqus/2022
    executables:
    - label: python_script
      instances:
      - command: python <<script_name>> <<args>>
        num_cores: 1
        parallel_mode: null
    - label: abaqus
      instances:
      - command: abq2022
        num_cores: 1
        parallel_mode: null

  task_schemas:
  - objective: run_abaqus
    inputs:
    - parameter: friction
    - parameter: conductance_value
    - parameter: conductance_file
    - parameter: power
    - parameter: inp_file
    outputs:
    - parameter: combine_outputs
    actions:
    - environments:
      - scope:
          type: any
        environment: abaqus_env
      input_file_generators:
      - input_file: new_inp_file
        from_inputs:
        - friction
        - conductance_value
        - conductance_file
        - power
        - inp_file
        script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/\
          Abaqus_bayesian_matflow/generate_input_file.py>>"
      commands:
      - command: <<executable:abaqus>> job=sub_script_check input=<<file:new_inp_file>> interactive
      - command: "<<executable:abaqus>> cae noGUI=/mnt/iusers01/support/mbexegc2/scratch/\
          Abaqus_bayesian_matflow/read_Force_PEEQ_NT11_barrelling_forcemac.py"
      save_files:
      - odb_file
      output_file_parsers:
        combine_outputs:
          from_files:
          # These files have been removed from `save_files` in the main action above due to a bug.
          # They're automatically saved when they are listed as `from_files`.
          - force_sample_set_1
          - force_sample_set_2
          - nt11
          - outer_sample_xcoords
          - peeq_output
          script: "<<script:/mnt/iusers01/support/mbexegc2/scratch/\
           Abaqus_bayesian_matflow/gather_odb_outputs.py>>"
          save_files:
          - odb_results

  command_files:
  - label: new_inp_file
    name:
      name: friction_conductance.inp
  - label: odb_file
    name:
      name: sub_script_check.odb
  - label: force_sample_set_1
    name:
      name: Force_sample_set1.rpt
  - label: force_sample_set_2
    name:
      name: Force_sample_set2.rpt
  - label: nt11
    name:
      name: NT11.rpt
  - label: outer_sample_xcoords
    name:
      name: outer_sample_xcoords.rpt
  - label: peeq_output
    name:
      name: PEEQ_output.rpt
  - label: odb_results
    name:
      name: odb_results.json

tasks:
- schema: run_abaqus
  inputs:
    power: 0
    inp_file: /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/800C_1s-1_setup.inp
  sequences:
  - path: inputs.conductance_value
    values:
    - 0
    - 100
    - 200
    nesting_order: 0
  - path: inputs.conductance_file
    values:
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/800nocondC_heatup22.odb"
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/80010C_heatup22.odb"
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/80020C_heatup22.odb"
    nesting_order: 0
  - path: inputs.friction
    values:
    - 0.01
    - 0.08
    - 0.15
#    - 0.22
#    - 0.29
#    - 0.36
#    - 0.43
#    - 0.5
#    - 0.57
#    - 0.64
#    - 0.71
#    - 0.78
#    - 0.85
#    - 0.92
#    - 0.99
    nesting_order: 1
